services:
  postgresdb:
    container_name: ${POSTGRES_CONTAINER}
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ../docker/pgdata:/var/lib/postgresql/data
      - ../docker/db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
